### ISSUE TITLE
Add flag to strip bom from input

### ISSUE THREAD

**Issue by jayvdb** [timrburnham/bom_open#1]
Many tools cant handle the bom, causing them to blow up on the first chars.

It would be useful to strip that out efficiently.

**Comment by jayvdb** [comment]
https://github.com/1441302031/luaGameFramework/blob/05a7a34a351c081efe76726d0f314a5e4bd4eefe/MyLuaGame/remove_bom.py looks quite complete.

**Comment by jayvdb** [comment]
Actually it looks like the re-open process does strip the bom.  I need to build some real tests to be confident.

**Comment by timrburnham** [comment]
Yes, that's the biggest reason I wrote this tiny lib. After we've peeped the correct encoding with chardet, Python's builtin stream handling handles the rest. If a BOM is present (utf-8-sig, for instance), correct decoding from bytes to string requires the removal of BOM. This isn't done with default utf-8 encoding, and sadly Python never checks of its own accord.

**Comment by jayvdb** [comment]
The tests already confirm this for the file re-open.

It would also be helpful to ensure this can be achieved for stream `sys.stdin`, which is often used instead of a file, and regularly suffers from BOM's appearing when using pipes in Powershell.

**Comment by jayvdb** [comment]
Just fyi, my initial testing (and code inspection) indicates that the BOM isnt stripped if `encoding` is specified, both for stdin, and for files.

It isnt really defined behaviour yet.   I expected it would strip the bom - there I am assuming that using `encoding` limits the encoding I am expecting to only the one encoding, and I expect it to strip the bom because this is called "bom_open". 

This could be quite easily fixed by replacing encoding='utf-8' with encoding='utf-8-sig', which will strip the bom.

And https://github.com/timrburnham/bom_open/issues/10 could help with that for stdin.

Still trying to get a nice mock of stdin that doesnt break because of https://github.com/timrburnham/bom_open/issues/12

**Comment by jayvdb** [comment]
There is at least one major codec, GB18030, which doesnt strip the bom automatically, and it also trips chardet atm https://github.com/chardet/chardet/issues/178

**Comment by jayvdb** [comment]
Also worth noting that there are wrapper implementations, like this one, in other languages http://www.kendar.org/?p=/dotnet/bomlocale and dedicated libraries like https://crates.io/crates/unicode_bom/1.1.1
