### ISSUE TITLE
Fails if stdin does not have a buffer attribute

### ISSUE THREAD

**Issue by jayvdb** [timrburnham/bom_open#12]
While the real sys.stdin does have a buffer attribute, often mocks of `sys.stdin` do not.

In order to not fail when subjected to testing, bom_open needs to gracefully handle sys.stdin not having a `buffer`.  It could emit a message on stderr to indicate that it has encountered an odd-looking `sys.stdin`.

**Comment by timrburnham** [comment]
I think I favor finding a different test over changing the library to work around the mock. Spawning a real subprocess and giving it a real pipe seems to [work](https://travis-ci.org/timrburnham/bom_open/builds/564183945?utm_source=github_status&utm_medium=notification), except in Python 3.4 which didn't have `subprocess.run` yet. I'll re-write the test to use the [older high-level API](https://docs.python.org/3/library/subprocess.html#call-function-trio) here pretty soon.

**Comment by jayvdb** [comment]
I am not so concerned about our tests.  It is users of the library, and their tests which will fail, if they are using a mock which doesnt emulate stdin very closely.

We could recommend libraries with mocks which do work.  And fix ones that don't.
e.g. https://github.com/bskinn/stdio-mgr/pull/25

But that is a never ending battle.

If we were to alter the library to allow `.buffer` to be missing, we'd need to be careful that the workarounds required are not run in normal operations.  We could even look for envvar `CI` or a custom envvar before allowing them.

If we did this, it makes it much easier to drop `bom_open` into other libraries as a drop-in replacement.  Typically the types of repos which care about boms in streams also have copious tests with mocks.

**Comment by timrburnham** [comment]
Closing due to #14
