### ISSUE TITLE
Windows CI

### ISSUE THREAD

**Issue by jayvdb** [timrburnham/bom_open#15]
This library needs Windows CI.  It could be AppVeyor, Azure, and the Travis Windows beta is also worth considering.

My recent thoughts on them at https://github.com/storyscript/storyscript/issues/1037 .  I'm happy to implement whichever you prefer, or wait until you've done it, or I'll do AppVeyor in a few days and you can make a decision then.

**Comment by timrburnham** [comment]
I would welcome any contribution on this. My very slight preference would be to keep CI centralized in one place, currently Travis but I could easily be persuaded otherwise.
