### ISSUE TITLE
No defined behaviour for when encoding is specified

### ISSUE THREAD

**Issue by jayvdb** [timrburnham/bom_open#18]
When the caller provides a value for `encoding`, there isnt a clear definition/documentation of what would happen.

The readme implicitly says that providing an encoding will cause `bom_open` to behave like `open`.  If that is the best solution, then it should be explicitly documented.

One easy improvement is to replace `encoding='utf-8'` with `encoding='utf-8-sig'`, which will strip the bom, and has no negative effects, however the file object `.encoding` will be `utf-8-sig` instead of the expected `utf-8`.

IMO `encoding='utf-16'` would also be sensible, and would automatically handle utf16's boms, but would reject utf-8 and utf-32.  This could be used when the caller wants to be strict about the file types it permits, but doesnt want to be concerned with the endian-ness of the host.  This helps for e.g. if the program needs to interoperate with other tools which have limitations.

Similarly in py3.7+ many file objects will now have a `reconfigure` which could be used - c.f. https://github.com/timrburnham/bom_open/issues/10

**Comment by timrburnham** [comment]
All valid utf-16 files have a bom, and `encoding='utf-16'` strips it correctly. Also, chardet labels both LE and BE files as simply utf-16, thereby letting the decoder strip bom.

For utf-8, this is now resolved in #20
