### ISSUE TITLE
Minimum setuptools 38.6.0

### ISSUE THREAD

**Issue by jayvdb** [timrburnham/bom_open#2]
A minimum setuptools of `setuptools>=38.6.0` seems unnecessary; there doesn't appear to be any dependency on setuptools for the installation process.

It may be that version of setuptools helps the packaging&release process, but that is separate from the installation process.

**Comment by timrburnham** [comment]
Yes, I was packaging this at the time Pypi was moving to Warehouse and adding Markdown support. I didn't feel like writing RST, and older setuptools didn't build the MD correctly for Pypi. It's easier to remove now than back then.
