### ISSUE TITLE
Handle compressed encodings

### ISSUE THREAD

**Issue by jayvdb** [timrburnham/bom_open#23]
Compressed encodings also have a detectable magic prefix in the stream, which could be used to determine how to open a compressed textual stream.  This is slightly out of scope, as the magic are not a bom, so it is reasonable to declare that this shouldn't be part of 'bom open' as it belongs more in a 'magic open'.  And there are existing libraries which already handle "decompress this stream, whatever encoding it is using", but those libraries then dont decode the text streams.  Worth considering.

**Comment by timrburnham** [comment]
That's a pretty good idea for a secondary project, but yeah, I would consider it out of scope for this library. Besides, there's only a limited number of stream-encoding mechanisms which can be transparently decompressed--gzip comes to mind--but most require seeking back/forwards thru a file, and bring the option of multiplexing multiple files into a single (let's say) zip. That sort of thing is probably better handled with application logic, and with metadata hint such as HTTP Accept-Encoding... Requests library already handles that nicely, for instance.

**Comment by jayvdb** [comment]
ok
